# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox
        run: pipx install tox
      - name: Run linters
        run: tox run -e lint

  check-version:
    name: Check version
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install yq
        run: sudo snap install yq
      - name: Compare versions
        run: |
          APP=$(yq .name rockcraft.yaml)
          ROCK_VERSION=$(yq .version rockcraft.yaml)
          CHANNEL=$(yq ".parts.charmed-mysql.stage-snaps[0]" rockcraft.yaml \
            | cut -c15-)
          SNAP_VERSION=$(snap info $APP | grep $CHANNEL | awk -F ' ' \
            '{print $2}')
          if [ "$ROCK_VERSION" != "$SNAP_VERSION" ]; then
              echo "VERSION MISMATCH DETECTED"
              echo "Rock version: $ROCK_VERSION"
              echo "SNAP version: $SNAP_VERSION"
              exit 1
          fi

  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v29.0.4
